'use client';
import {useEffect,useState} from 'react';
import type {Content} from '@/lib/content';
import {SectionContent} from '../reception';
import {registerEditorTools} from '@/lib/webmcp';
const uid=()=>crypto.randomUUID();
function Field({label,value,onChange,area=false}:{label:string,value:string,onChange:(v:string)=>void,area?:boolean}){return <label className="field">{label}{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Ordering({index,total,move,remove}:{index:number,total:number,move:(d:number)=>void,remove:()=>void}){return <div className="admin-actions"><button className="secondary" disabled={index===0} onClick={()=>move(-1)} aria-label="Posunout nahoru">↑ Nahoru</button><button className="secondary" disabled={index===total-1} onClick={()=>move(1)} aria-label="Posunout dolů">↓ Dolů</button><button className="danger" onClick={()=>{if(confirm('Opravdu chcete tuto položku odstranit? Změna se projeví po uložení.'))remove()}}>Odstranit</button></div>}
function Photo({photo,change}:{photo:{src:string,alt:string,focus:number},change:(p:{src?:string,alt?:string,focus?:number})=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <div className="admin-row"><div>{photo.src&&<img className="admin-thumb" src={photo.src} alt={photo.alt} style={{objectPosition:`50% ${photo.focus}%`}}/>}<label className="field">{busy?'Nahrávám…':'Nahrát / vyměnit fotografii'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5000000){setError('Maximální velikost je 5 MB.');return}setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:form});const j=await r.json() as {src:string,error?:string};if(!r.ok)throw Error(j.error);change({src:j.src})}catch(e){setError(e instanceof Error?e.message:'Nahrání se nezdařilo.')}finally{setBusy(false)}}}/></label><small>JPG, PNG nebo WebP, maximálně 5 MB.</small>{error&&<p role="alert">{error}</p>}{photo.src&&<button className="secondary" onClick={()=>{if(confirm('Odstranit fotografii z tohoto profilu?'))change({src:''})}}>Odebrat fotografii</button>}</div><div className="form-grid"><Field label="Popis fotografie pro čtečky obrazovky" value={photo.alt} onChange={alt=>change({alt})}/><label className="field">Hlavní bod fotografie: {photo.focus} %<input type="range" min="0" max="100" value={photo.focus} onChange={e=>change({focus:Number(e.target.value)})}/></label><small>Posuvníkem upravíte svislý ořez. Náhled ukazuje aktuální nastavení.</small></div></div>}
export default function AdminEditor(){
 useEffect(registerEditorTools,[]);
 const [data,setData]=useState<Content|null>(null),[revision,setRevision]=useState(0),[tab,setTab]=useState('cenik'),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false);
 useEffect(()=>{fetch('/api/content').then(async r=>{const j=await r.json() as {data:Content,revision:number,error?:string};if(!r.ok)throw Error(j.error);setData(j.data);setRevision(j.revision)}).catch(e=>setStatus(e.message))},[]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',before);return()=>removeEventListener('beforeunload',before)},[dirty]);
 const edit=(fn:(d:Content)=>void)=>{setData(d=>{if(!d)return d;const copy=structuredClone(d);fn(copy);return copy});setDirty(true);setStatus('Neuložené změny');};
 const move=<T,>(arr:T[],i:number,delta:number)=>{const j=i+delta;if(j>=0&&j<arr.length)[arr[i],arr[j]]=[arr[j],arr[i]]};
 async function save(publish:boolean){if(publish&&!confirm('Zveřejnit aktuální obsah na webu?'))return;setBusy(true);try{const r=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data,revision,publish})});const j=await r.json() as {revision:number,message:string,error?:string};if(!r.ok)throw Error(j.error);setRevision(j.revision);setStatus(j.message);setDirty(false)}catch(e){setStatus(e instanceof Error?e.message:'Uložení se nezdařilo.')}finally{setBusy(false)}}
 if(!data)return <main className="admin"><h1>Správa obsahu</h1><p role="status">{status||'Načítám obsah…'}</p><a href="/admin">Zkusit znovu</a></main>;
 return <main className="admin"><header><div><div className="eyebrow">Zuby | Dásně</div><h1>Správa obsahu</h1></div><div className="admin-actions"><a href="/" target="_blank" rel="noreferrer">Otevřít web ↗</a><a href="/signout-with-chatgpt?return_to=/" target="_top">Odhlásit se</a></div></header><p>Změny nejprve uložte jako koncept. Návštěvníci je uvidí až po zveřejnění.</p><div className="admin-toolbar"><button className="secondary" disabled={busy} onClick={()=>void save(false)}>Uložit koncept</button><button className="primary" disabled={busy} onClick={()=>void save(true)}>Zveřejnit změny</button><button className="secondary" onClick={()=>setPreview(!preview)}>{preview?'Zpět k úpravám':'Náhled konceptu'}</button><span role="status">{busy?'Ukládám…':status}</span></div><nav className="admin-tabs" aria-label="Upravit sekci">{[['cenik','Ceník'],['nas-tym','Náš tým'],['o-nas','O nás'],['prubeh-lecby','Průběh léčby'],['kontakt','Kontakt'],['objednani','Objednání']].map(([id,label])=><button className="secondary" aria-pressed={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {preview?<div className="admin-card"><h2>Náhled konceptu</h2><SectionContent id={tab} data={data}/></div>:<fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}>
 {tab==='cenik'&&<><Field label="Poznámka k ceníku" value={data.priceNote} area onChange={v=>edit(d=>{d.priceNote=v})}/>{data.categories.map((c,ci)=><section className="admin-card" key={c.id}><Field label="Název kategorie" value={c.name} onChange={v=>edit(d=>{d.categories[ci].name=v})}/><Ordering index={ci} total={data.categories.length} move={delta=>edit(d=>move(d.categories,ci,delta))} remove={()=>edit(d=>{d.categories.splice(ci,1)})}/>{c.items.map((p,pi)=><div className="admin-card" key={p.id} style={{marginTop:20}}><div className="admin-row"><Field label="Název položky" value={p.name} onChange={v=>edit(d=>{d.categories[ci].items[pi].name=v})}/><Field label="Cena nebo rozpětí (včetně Kč)" value={p.price} onChange={v=>edit(d=>{d.categories[ci].items[pi].price=v})}/><Field label="Jednotka (nepovinné)" value={p.unit} onChange={v=>edit(d=>{d.categories[ci].items[pi].unit=v})}/><Field label="Poznámka (nepovinné)" value={p.note} onChange={v=>edit(d=>{d.categories[ci].items[pi].note=v})}/></div><Ordering index={pi} total={c.items.length} move={delta=>edit(d=>move(d.categories[ci].items,pi,delta))} remove={()=>edit(d=>{d.categories[ci].items.splice(pi,1)})}/></div>)}<button className="secondary" onClick={()=>edit(d=>{d.categories[ci].items.push({id:uid(),name:'Nová položka',price:'',unit:'',note:''})})}>+ Přidat položku</button></section>)}<button className="secondary" onClick={()=>edit(d=>{d.categories.push({id:uid(),name:'Nová kategorie',items:[]})})}>+ Přidat kategorii</button></>}
 {tab==='nas-tym'&&<><h2>Členové týmu ({data.team.length})</h2>{data.team.map((p,i)=><section className="admin-card" key={p.id}><h3>{p.name}</h3><div className="admin-row">{(['name','title','role','description'] as const).map((key,k)=><Field key={key} label={['Jméno a příjmení','Titul','Role','Popis'][k]} area={key==='description'} value={p[key]} onChange={v=>edit(d=>{d.team[i][key]=v})}/>)}</div><Photo photo={p} change={v=>edit(d=>{Object.assign(d.team[i],v)})}/><label><input type="checkbox" checked={p.hidden} onChange={e=>edit(d=>{d.team[i].hidden=e.target.checked})}/> Skrýt profil na webu</label><Ordering index={i} total={data.team.length} move={delta=>edit(d=>move(d.team,i,delta))} remove={()=>edit(d=>{d.team.splice(i,1)})}/></section>)}<button className="secondary" onClick={()=>edit(d=>{d.team.push({id:uid(),name:'Nový zaměstnanec',title:'',role:'',description:'',src:'',alt:'',focus:50,hidden:false})})}>+ Přidat zaměstnance</button></>}
 {tab==='o-nas'&&<><h2>Texty O nás</h2>{data.about.map((p,i)=><div className="admin-card" key={i}><Field label={'Odstavec '+(i+1)} value={p} area onChange={v=>edit(d=>{d.about[i]=v})}/><Ordering index={i} total={data.about.length} move={delta=>edit(d=>move(d.about,i,delta))} remove={()=>edit(d=>{d.about.splice(i,1)})}/></div>)}<button className="secondary" onClick={()=>edit(d=>{d.about.push('')})}>+ Přidat odstavec</button><h2>Fotografie ordinace</h2>{data.photos.map((p,i)=><div className="admin-card" key={p.id}><Photo photo={p} change={v=>edit(d=>{Object.assign(d.photos[i],v)})}/><Ordering index={i} total={data.photos.length} move={delta=>edit(d=>move(d.photos,i,delta))} remove={()=>edit(d=>{d.photos.splice(i,1)})}/></div>)}<button className="secondary" onClick={()=>edit(d=>{d.photos.push({id:uid(),src:'',alt:'',focus:50})})}>+ Přidat fotografii</button></>}
 {tab==='prubeh-lecby'&&<>{data.steps.map((p,i)=><div className="admin-card" key={p.id}><Field label="Název kroku" value={p.title} onChange={v=>edit(d=>{d.steps[i].title=v})}/><Field label="Popis kroku" value={p.text} area onChange={v=>edit(d=>{d.steps[i].text=v})}/><Ordering index={i} total={data.steps.length} move={delta=>edit(d=>move(d.steps,i,delta))} remove={()=>edit(d=>{d.steps.splice(i,1)})}/></div>)}<button className="secondary" onClick={()=>edit(d=>{d.steps.push({id:uid(),title:'Nový krok',text:''})})}>+ Přidat krok</button></>}
 {tab==='kontakt'&&<><div className="admin-card"><div className="admin-row">{(['phone','email','address','map','facebook','instagram'] as const).map((key,i)=><Field key={key} label={['Telefon','E-mail','Adresa','Odkaz na mapu','Facebook URL','Instagram URL'][i]} value={data.contact[key]} onChange={v=>edit(d=>{d.contact[key]=v})}/>)}</div></div><h2>Otevírací doba</h2>{data.contact.hours.map((h,i)=><div className="admin-row" key={i}><Field label="Den" value={h.day} onChange={v=>edit(d=>{d.contact.hours[i].day=v})}/><Field label="Čas / zavřeno" value={h.time} onChange={v=>edit(d=>{d.contact.hours[i].time=v})}/></div>)}</>}
 {tab==='objednani'&&<div className="admin-card"><Field label="Informace nad formulářem" value={data.bookingNote} area onChange={v=>edit(d=>{d.bookingNote=v})}/><p>Online objednávání je neaktivní. Formulář žádné údaje neodesílá ani neukládá.</p></div>}
 </fieldset>}</main>;
}
