'use client';
import {useEffect,useRef,useState} from 'react';
import {Heart,Users,Route,ReceiptText,MapPin,CalendarDays,ArrowUpRight,X,Phone,Mail} from 'lucide-react';
import type {Content} from '@/lib/content';
const sections=[{id:'o-nas',name:'O nás',Icon:Heart},{id:'nas-tym',name:'Náš tým',Icon:Users},{id:'prubeh-lecby',name:'Průběh léčby',Icon:Route},{id:'cenik',name:'Ceník',Icon:ReceiptText},{id:'kontakt',name:'Kontakt',Icon:MapPin},{id:'objednani',name:'Objednání',Icon:CalendarDays}];
export function SectionContent({id,data}:{id:string,data:Content}){
 const [message,setMessage]=useState('');
 if(id==='o-nas')return <><div className="prose">{data.about.map((p,i)=><p key={i}>{p}</p>)}</div><div className="gallery">{data.photos.filter(p=>p.src).map(p=><img key={p.id} src={p.src} alt={p.alt} loading="lazy" style={{objectPosition:`50% ${p.focus}%`}}/>)}</div></>;
 if(id==='nas-tym')return <div className="team-grid">{data.team.filter(p=>!p.hidden).map(p=><article className="person" key={p.id}>{p.src&&<img src={p.src} alt={p.alt} loading="lazy" style={{objectPosition:`50% ${p.focus}%`}}/>}<div className="person-text"><h3>{p.title==='MDDr.'?'MDDr. ':''}{p.name}{p.title&&p.title!=='MDDr.'?', '+p.title:''}</h3><p>{p.role}</p>{p.description&&<p className="bio">{p.description}</p>}</div></article>)}</div>;
 if(id==='prubeh-lecby')return <ol className="steps">{data.steps.map((s,i)=><li key={s.id}><span className="step-no">{String(i+1).padStart(2,'0')}</span><div><h3>{s.title}</h3><p>{s.text}</p></div></li>)}</ol>;
 if(id==='cenik')return <><p className="notice">{data.priceNote}</p>{data.categories.map(c=><section className="price-group" key={c.id}><h3>{c.name}</h3>{c.items.map(p=><div className="price-row" key={p.id}><div>{p.name}{p.note&&<small>{p.note}</small>}</div><strong>{p.price}{p.unit&&` / ${p.unit}`}</strong></div>)}</section>)}</>;
 if(id==='kontakt')return <div className="contact-grid"><div><h3>Telefon, e-mail, adresa, sítě</h3><div className="contact-links"><a href={'tel:'+data.contact.phone.replace(/\s/g,'')}><Phone size={20}/>{data.contact.phone}</a><a href={'mailto:'+data.contact.email}><Mail size={20}/>{data.contact.email}</a><a href={data.contact.map} target="_blank" rel="noreferrer"><MapPin size={22}/>{data.contact.address}</a></div><div className="socials"><a href={data.contact.facebook} target="_blank" rel="noreferrer">Facebook</a><a href={data.contact.instagram} target="_blank" rel="noreferrer">Instagram</a></div></div><div><h3>Otevírací doba</h3><table className="hours"><tbody>{data.contact.hours.map(h=><tr key={h.day}><td>{h.day}</td><td>{h.time}</td></tr>)}</tbody></table></div></div>;
 return <div className="booking-layout"><div><h3 style={{fontSize:'2rem',marginBottom:20}}>Objednací formulář</h3><p className="notice">{data.bookingNote}</p><div className="contact-links"><a href={'tel:'+data.contact.phone.replace(/\s/g,'')}><Phone size={20}/>{data.contact.phone}</a><a href={'mailto:'+data.contact.email}><Mail size={20}/>{data.contact.email}</a></div></div><form className="form-grid" onSubmit={e=>{e.preventDefault();setMessage('Údaje nebyly odeslány ani uloženy. Online objednávání zatím není aktivní.');}}><label className="field">Jméno a příjmení *<input name="name" autoComplete="name" required maxLength={150}/></label><label className="field">E-mail *<input type="email" name="email" autoComplete="email" required maxLength={200}/></label><label className="field">Telefon *<input type="tel" name="phone" autoComplete="tel" required pattern="\+?[0-9\s\-]{9,18}" title="Zadejte telefonní číslo, případně s předvolbou."/></label><label className="field">Vaše zpráva (nepovinné)<textarea name="message" maxLength={2000}/></label><small>Formulář je ukázkový. Vaše údaje se nikam neodesílají.</small><button className="primary" type="submit">Vyzkoušet formulář</button>{message&&<p className="form-status" role="status">{message}</p>}<a href="/source/Podminky_ochrany_osobnich-udaju-ZUBY_DASNE.pdf" target="_blank" rel="noreferrer">Ochrana osobních údajů</a></form></div>;
}
export default function Reception({data}:{data:Content}){
 const [active,setActive]=useState<string|null>(null),[ready,setReady]=useState(false);
 const panel=useRef<HTMLDivElement>(null),scene=useRef<HTMLElement>(null),closeButton=useRef<HTMLButtonElement>(null),previous=useRef<string|null>(null),animation=useRef<Animation|null>(null),closing=useRef(false);
 useEffect(()=>{setReady(true);const sync=()=>{const id=location.hash.slice(1);setActive(sections.some(s=>s.id===id)?id:null)};sync();addEventListener('popstate',sync);addEventListener('hashchange',sync);return()=>{removeEventListener('popstate',sync);removeEventListener('hashchange',sync)}},[]);
 useEffect(()=>{if(!active||!panel.current)return;const p=panel.current;const tile=document.getElementById('tile-'+active);const a=tile?.getBoundingClientRect(),b=p.getBoundingClientRect();previous.current=active;scene.current?.setAttribute('inert','');document.body.style.overflow='hidden';if(a&&!matchMedia('(prefers-reduced-motion: reduce)').matches){animation.current=p.animate([{transform:`translate(${a.left-b.left}px,${a.top-b.top}px) scale(${a.width/b.width},${a.height/b.height})`,borderRadius:'24px',opacity:.6},{transform:'none',borderRadius:'32px',opacity:1}],{duration:480,easing:'cubic-bezier(.22,1,.36,1)'});}closeButton.current?.focus();return()=>{animation.current?.cancel();scene.current?.removeAttribute('inert');document.body.style.overflow='';document.getElementById('tile-'+previous.current)?.focus()}},[active]);
 function open(id:string){history.pushState({section:true},'',`#${id}`);setActive(id)}
 async function close(){if(!active||!panel.current||closing.current)return;closing.current=true;const p=panel.current,t=document.getElementById('tile-'+active),a=t?.getBoundingClientRect(),b=p.getBoundingClientRect();animation.current?.cancel();if(a&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const anim=p.animate([{transform:'none',opacity:1},{transform:`translate(${a.left-b.left}px,${a.top-b.top}px) scale(${a.width/b.width},${a.height/b.height})`,opacity:0}],{duration:350,easing:'cubic-bezier(.4,0,.2,1)'});try{await anim.finished}catch{}}if(history.state?.section)history.back();else {history.replaceState(null,'',location.pathname);setActive(null)}closing.current=false;}
 return <><div className="reception-bg" aria-hidden="true"/><main className="scene" ref={scene}><header className="topline"><span>Stomatologické centrum</span><a href={'tel:'+data.contact.phone.replace(/\s/g,'')}><Phone size={15}/>{data.contact.phone}</a></header><div className="stage"><div className="intro"><img className="brand" src="/source/secondarylogowhite.svg" alt="ZUBY | DÁSNĚ"/><h1>{data.intro}</h1><p>{(data.about[0]||'').split('.').slice(1,2).join('.').trim()}.</p></div><nav className="tiles" aria-label="Hlavní sekce">{sections.map(({id,name,Icon})=><a key={id} id={'tile-'+id} href={'#'+id} aria-haspopup="dialog" className={'tile '+(id==='objednani'?'booking':'')} onClick={e=>{e.preventDefault();open(id)}}><Icon aria-hidden="true"/><span>{name}</span><ArrowUpRight className="tile-arrow" aria-hidden="true"/></a>)}</nav></div><footer className="footline"><span>{data.contact.address}</span><a className="admin-link" href="/admin">Správa obsahu</a></footer></main>{active&&<><div className="veil" aria-hidden="true"/><div className="panel" ref={panel} role="dialog" aria-modal="true" aria-labelledby="section-title" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();void close()}if(e.key==='Tab'){const nodes=panel.current?.querySelectorAll<HTMLElement>('a[href],button,input,textarea,select,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header className="panel-head"><div><div className="eyebrow">Zuby | Dásně</div><h2 id="section-title">{sections.find(s=>s.id===active)?.name}</h2></div><button className="close" ref={closeButton} aria-label="Zavřít sekci" onClick={()=>void close()}><X size={23}/></button></header><div className="panel-scroll" key={active}><SectionContent id={active} data={data}/></div></div></>}{!ready&&<div className="fallback-content">{sections.map(s=><section key={s.id} id={s.id}><h2>{s.name}</h2><SectionContent id={s.id} data={data}/></section>)}</div>}</>;
}
