import assert from 'node:assert/strict';
import {createHandler,config} from '../netlify/functions/web.mjs';
import {getStore} from '@netlify/blobs';
import {BlobsServer} from '@netlify/blobs/server';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomBytes} from 'node:crypto';

// Use Netlify's actual SDK and local Blobs server, with isolated temporary data.
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zuby-netlify-test-'));
const token=randomBytes(32).toString('hex');
let server=new BlobsServer({directory,token});
let address=await server.start();
const store=name=>getStore({name,siteID:'zuby-test',token,apiURL:`http://127.0.0.1:${address.port}`,consistency:'strong'});
const stores=()=>({content:store('content'),media:store('media')});
let handler=createHandler(stores);
const origin='https://example.netlify.app';let cookie='';
const request=(url,method='GET',body,auth=true,extra={})=>{
 const pathname=new URL(origin+url).pathname;
 assert.ok(config.path.some(route=>route.endsWith('*')?pathname.startsWith(route.slice(0,-1)):pathname===route),`Netlify must route ${pathname} to the function`);
 return handler(new Request(origin+url,{method,headers:{...(auth?{cookie}:{}),...(method!=='GET'?{Origin:origin}:{}),...extra},...(body!==undefined?{body}:{})}));
};
try{
 delete process.env.ADMIN_PASSWORD;
 assert.equal((await request('/admin/login')).status,503);
 process.env.ADMIN_PASSWORD=randomBytes(32).toString('hex');
 assert.equal((await request('/admin')).status,303);
 assert.equal((await request('/admin/')).status,303);
 const loginPage=await request('/admin/login/');assert.equal(loginPage.status,200);assert.match(await loginPage.text(),/action="\/admin\/login"/);
 assert.equal((await request('/api/content','GET',undefined,false,{'oai-authenticated-user-id':'owner'})).status,403);
 assert.equal((await request('/admin/login','POST','password=wrong')).status,403);
 assert.equal((await request('/admin/login','POST','password='+process.env.ADMIN_PASSWORD,true,{Origin:'https://evil.example'})).status,403);
 const login=await request('/admin/login','POST','password='+process.env.ADMIN_PASSWORD);
 cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Strict/);
 assert.equal((await request('/admin')).status,200);
 assert.equal((await request('/admin/')).status,200);
 let {data,revision}=await (await request('/api/content')).json();
 // Simulate content saved before announcements existed.
 const legacy=structuredClone(data);delete legacy.announcement;
 await stores().content.setJSON('state',{draft:legacy,published:legacy,revision});
 assert.equal((await (await request('/api/content')).json()).data.announcement,'');
 const original=await (await request('/')).text();assert.match(original,/bootstrap/);assert.ok(!original.includes('home-announcement'));
 // Both languages are rendered on the server, without optional requests before consent.
 assert.match(original,/<html lang="cs">/);assert.ok(original.includes('cookie-banner'));assert.ok(!original.includes('<iframe'));
 const enResponse=await request('/?lang=en');assert.equal(enResponse.headers.get('set-cookie'),null);
 const enHtml=await enResponse.text();assert.match(enHtml,/<html lang="en">/);assert.ok(enHtml.includes('About us'));assert.ok(enHtml.includes('Root canal treatment'));assert.ok(enHtml.includes('Dental hygienist'));assert.ok(enHtml.includes('Accept cookies'));assert.ok(!enHtml.includes('<iframe'));
 assert.match(enHtml,/hreflang="cs"/);assert.match(enHtml,/hreflang="en"/);
 const remembered=await (await request('/','GET',undefined,false,{cookie:'zuby_consent=v1-accepted; zuby_lang=en'})).text();
 assert.match(remembered,/<html lang="en">/);assert.ok(!remembered.includes('class="cookie-banner"'));assert.ok(remembered.includes('<iframe'));
 const rejected=await (await request('/','GET',undefined,false,{cookie:'zuby_consent=v1-rejected; zuby_lang=en'})).text();
 assert.match(rejected,/<html lang="cs">/);assert.ok(!rejected.includes('class="cookie-banner"'));assert.ok(!rejected.includes('<iframe'));
 const explicit=await (await request('/?lang=cs','GET',undefined,false,{cookie:'zuby_consent=v1-accepted; zuby_lang=en'})).text();assert.match(explicit,/<html lang="cs">/);
 const invalidConsent=await (await request('/?lang=xx','GET',undefined,false,{cookie:'zuby_consent=invalid; zuby_lang=en'})).text();assert.match(invalidConsent,/<html lang="cs">/);assert.ok(invalidConsent.includes('class="cookie-banner"'));
 const announcement='Mimořádně zavřeno v pátek.\nZnovu otevřeme v pondělí. <b>Děkujeme</b>';
 data.announcement=announcement;data.english={[announcement]:'Special opening hours announcement',[data.categories[0].items[0].name]:'Updated English consultation'};
 data.team[0].name='Test přetrvání';data.team[0].hidden=true;data.priceNote='Nová poznámka testu';
 assert.equal((await request('/api/content','PUT',JSON.stringify({data,revision}))).status,200);
 assert.ok(!(await (await request('/')).text()).includes('Nová poznámka testu'));
 assert.ok(!(await (await request('/')).text()).includes('home-announcement'));
 await server.stop();server=new BlobsServer({directory,token});address=await server.start();
 handler=createHandler(stores); // Restart storage and handler, preserving disk contents.
 let draft=await (await request('/api/content')).json();assert.equal(draft.data.priceNote,'Nová poznámka testu');assert.equal(draft.data.announcement,announcement);assert.equal(draft.data.english[announcement],'Special opening hours announcement');
 assert.ok(!(await (await request('/?lang=en')).text()).includes('Special opening hours announcement'),'English draft is not public');
 assert.equal((await request('/api/content','PUT',JSON.stringify({data,revision,publish:true}))).status,409);
 assert.equal((await request('/api/content','PUT',JSON.stringify({data,revision:draft.revision,publish:true}))).status,200);
 const page=await (await request('/')).text();assert.ok(page.includes('Nová poznámka testu'));assert.ok(!page.includes('Test přetrvání'));
 assert.match(page,/class="notice home-announcement"/);assert.ok(page.indexOf('home-announcement')<page.indexOf('aria-label="Hlavní sekce"'));
 assert.ok(page.includes('&lt;b&gt;Děkujeme&lt;/b&gt;'));assert.ok(!page.includes('<b>Děkujeme</b>'));
 const publishedEnglish=await (await request('/?lang=en')).text();assert.ok(publishedEnglish.includes('Special opening hours announcement'));assert.ok(publishedEnglish.includes('Updated English consultation'));assert.ok(publishedEnglish.includes(data.categories[0].items[0].price));
 const form=new FormData();form.set('file',new File([fs.readFileSync('public/recepce-logo.webp')],'photo.webp',{type:'image/webp'}));
 assert.equal((await request('/api/upload','POST',form,false)).status,403);
 const uploaded=await request('/api/upload','POST',form);assert.equal(uploaded.status,200);const {src}=await uploaded.json();
 await server.stop();server=new BlobsServer({directory,token});address=await server.start();
 handler=createHandler(stores);const photo=await request(src);assert.equal(photo.status,200);assert.equal(photo.headers.get('content-type'),'image/webp');
 assert.deepEqual(Buffer.from(await photo.arrayBuffer()),fs.readFileSync('public/recepce-logo.webp'));
 assert.ok((await (await request('/')).text()).includes('Nová poznámka testu'),'published content survives storage restart');
 assert.ok((await (await request('/')).text()).includes('home-announcement'),'published announcement survives restart');
 assert.ok((await (await request('/?lang=en')).text()).includes('Updated English consultation'),'English publication survives storage restart');
 let saved=await (await request('/api/content')).json();saved.data.announcement='';
 assert.equal((await request('/api/content','PUT',JSON.stringify(saved))).status,200);
 assert.ok((await (await request('/')).text()).includes('home-announcement'),'draft deletion is not published');
 saved=await (await request('/api/content')).json();
 assert.equal((await request('/api/content','PUT',JSON.stringify({...saved,publish:true}))).status,200);
 assert.ok(!(await (await request('/')).text()).includes('home-announcement'),'publishing empty text removes notice');
 saved=await (await request('/api/content')).json();saved.data.announcement='   \n  ';
 assert.equal((await request('/api/content','PUT',JSON.stringify({...saved,publish:true}))).status,200);
 assert.ok(!(await (await request('/')).text()).includes('home-announcement'),'whitespace does not render a notice');
 assert.equal((await (await request('/api/content')).json()).data.announcement,'');
 const invalid=new FormData();invalid.set('file',new File(['this is not a photo'],'fake.png',{type:'image/png'}));assert.equal((await request('/api/upload','POST',invalid)).status,400);
 assert.equal((await request('/api/content','PUT',JSON.stringify({data,revision:2}),false)).status,403);
 assert.match((await request('/signout-with-chatgpt')).headers.get('set-cookie'),/Max-Age=0/);
 process.env.ADMIN_PASSWORD=randomBytes(32).toString('hex');assert.equal((await request('/api/content')).status,403);
 console.log('PASS: bilingual SSR, consent/cookie language precedence, gated Google Maps, English CMS persistence, deployed route coverage, login, forged headers, origin, permissions, drafts, publish, announcement persistence/removal/escaping/legacy compatibility, revision conflict, hidden profile, upload, actual Blobs SDK/storage restarts, logout and password rotation.');
}finally{
 await server.stop();
 assert.equal(path.dirname(path.resolve(directory)),path.resolve(os.tmpdir()));
 assert.ok(path.basename(directory).startsWith('zuby-netlify-test-'));
 fs.rmSync(directory,{recursive:true,force:true});delete process.env.ADMIN_PASSWORD;
}
